app/urls.py
# urls.py
from django.urls import path
from .views import index, bolim_detail, fan_detail, vazifa_detail, quiz, submit_quiz, quiz_result

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('bolim/<int:bolim_id>/', bolim_detail, name='bolim_detail'),
    path('fan/<int:fan_id>/', fan_detail, name='fan_detail'),
    path('vazifa/<int:vazifa_id>/', vazifa_detail, name='vazifa_detail'),
    path('quiz/<int:vazifa_id>/', quiz, name='quiz'),
    path('submit_quiz/<int:vazifa_id>/', submit_quiz, name='submit_quiz'),
    path('quiz_result/', quiz_result, name='quiz_result'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('login.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import sign_up,sign_out

urlpatterns = [
    path('register/', sign_up, name='register'),
    path('signout/', sign_out, name='signout'),
]

app/models.py
from django.db import models

class Bolimlar(models.Model):
    Bolim = models.CharField(max_length=500)

    def __str__(self):
        return self.Bolim

class Fan(models.Model):
    Bolim = models.ForeignKey(Bolimlar, on_delete=models.CASCADE)
    Fan_nomi = models.CharField(max_length=200)
    Rasm = models.ImageField(upload_to='img')
    Ustoz = models.CharField(max_length=500)
    Ustoz_rasmi = models.ImageField(upload_to='ustoz')
    Malumot = models.TextField()

    def __str__(self):
        return self.Fan_nomi
class Vazifa(models.Model):
    Fan = models.ForeignKey(Fan, on_delete=models.CASCADE)
    nomi = models.TextField()
    video = models.FileField(upload_to='video')

    def __str__(self):
        return self.nomi

class Question(models.Model):
    nomi = models.ForeignKey(Vazifa, on_delete=models.CASCADE)
    text = models.TextField()
    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

app/views.py
# views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Bolimlar, Fan, Vazifa, Question, Answer

def index(request):
    bolimlar_list = Bolimlar.objects.all()
    return render(request, 'index.html', {'bolimlar_list': bolimlar_list})

def bolim_detail(request, bolim_id):
    bolim = get_object_or_404(Bolimlar, pk=bolim_id)
    fans = Fan.objects.filter(Bolim=bolim)
    return render(request, 'bolim_detail.html', {'bolim': bolim, 'fans': fans})

def fan_detail(request, fan_id):
    fan = get_object_or_404(Fan, pk=fan_id)
    vazifalar = Vazifa.objects.filter(Fan=fan)
    return render(request, 'fan_detail.html', {'fan': fan, 'vazifalar': vazifalar})

def vazifa_detail(request, vazifa_id):
    vazifa = get_object_or_404(Vazifa, pk=vazifa_id)
    questions = Question.objects.filter(nomi=vazifa)
    return render(request, 'vazifa_detail.html', {'vazifa': vazifa, 'questions': questions})

def quiz(request, vazifa_id):
    vazifa = get_object_or_404(Vazifa, pk=vazifa_id)
    questions = Question.objects.filter(nomi=vazifa)
    return render(request, 'quiz.html', {'vazifa': vazifa, 'questions': questions})


def submit_quiz(request, vazifa_id):
    if request.method == 'POST':
        score = 0
        total_questions = 0

        for question in Question.objects.filter(nomi__id=vazifa_id):
            total_questions += 1
            selected_answer_id = request.POST.get(f'question_{question.id}')

            if selected_answer_id:
                selected_answer = Answer.objects.get(pk=selected_answer_id)
                if selected_answer.is_correct:
                    score += 1

        return render(request, 'result.html', {'score': score, 'total_questions': total_questions})
    else:
        return redirect('quiz:quiz_index')

def quiz_result(request):
    return render(request, 'result.html', {})

login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout
from .forms import RegisterForm

def sign_up(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'registration/register.html', {'form': form})

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username
            user.save()
            messages.success(request, 'Muvaffaqiyatli ro\'yxatdan o\'tdingiz!')
            login(request, user)
            return redirect('/')  # Change 'post/' to the appropriate URL

    return render(request, 'registration/register.html', {'form': form})

def sign_out(request):
    logout(request)
    return redirect('/')  # Change 'home/' to the appropriate URL for your home page

templates/quiz.html
<!-- quiz.html -->
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz App</title>
    <style>
        body {
            background-color: #102439;
            margin-top: 100px;
        }

        h1 {
            color: #007bff;
            text-align: center;
        }

        form {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 30px;
        }

        fieldset {
            margin-bottom: 20px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 15px;
        }

        h2 {
            color: #007bff;
            font-size: 24px;
            font-weight: bold;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        button {
            background-color: #007bff;
            color: #ffffff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Quiz App</h1>
        <form method="post" action="{% url 'app:submit_quiz' vazifa.id%}">
            {% csrf_token %}
            
            {% for question in questions %}
                <fieldset>
                    <h2>{{ question.text }}</h2>
                    
                    {% for answer in question.answer_set.all %}
                        <div class="form-check">

                            <label class="form-check-label" for="answer_{{ answer.id }}">
                                <input class="form-check-input" type="radio" name="question_{{ question.id }}" id="answer_{{ answer.id }}" value="{{ answer.id }}"> {{ answer.text }}
                                <img src="" alt="">
                            </label>
                        </div>
                    {% endfor %}
                </fieldset>
            {% endfor %}

            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

{% endblock %}

templates/result.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 200px; text-align: center;">
  <h2>Natijangiz</h2>
  <p>Siz {{ total_questions }} ta savoldan / {{ score }} tasiga to'g'ri javob berdingiz!</p>
</div>
{% endblock %}